github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username if available
open_collective: # Replace with a single Open Collective username if you have a community collective
ko_fi: # Replace with a single Ko-fi username for one-time and small recurring donations
tidelift: # Replace with a single Tidelift platform-name/package-name if your project is part of the Tidelift subscription
community_bridge: # Replace with a single Community Bridge project-name if relevant
liberapay: # Replace with a single Liberapay username for donations
issuehunt: # Replace with a single IssueHunt username for funding specific issues
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name if applicable
polar: # Not commonly used, replace if applicable
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username for simple, one-time donations
thanks_dev: # Replace with a single thanks.dev username if using this platform
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
